RadioAssetManagement/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from RadioAssetManagement.views import index
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # voor taalwissel
]

urlpatterns += i18n_patterns(
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('helpdesk/', include('helpdesk.urls', namespace='helpdesk')),
    path('radio/', include('radio.urls', namespace='radio')),
    path('organization/', include('organization.urls', namespace='organization')),
    path('taqto/', include('taqto.urls')),
    path('printer/', include('printer.urls')),
    path('astrid/', include('astrid.urls')),
    path('roip/', include("roip.urls", namespace='roip')),
    path('fireplan/', include("fireplan.urls", namespace='fireplan')),
)

astrid/urls.py
# astrid/urls.py
from django.urls import path
from .views import *

app_name = 'astrid'

urlpatterns = [
    path('request/vtei', VTEIRequestCreateView.as_view(), name='vtei_request'),

    path('request/activation', ActivationRequestCreateView.as_view(), name='activation_request'),

    path('request/<int:pk>', RequestDetailView.as_view(), name='request_detail'),

    path('requests', RequestOverviewView.as_view(), name='request_overview'),

    path('subscritpions/upload', UploadSubscriptionsView.as_view(), name='upload_subscriptions'),

]

fireplan/urls.py
# fireplan/urls.py

from django.urls import path
from .views import *

app_name = 'fireplan'

urlpatterns = [
    path(
        "inventories/",
        LatestInventoryPerVectorView.as_view(),
        name="latest_inventory_per_vector",
    ),
]

radio/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import *


app_name = 'radio'

urlpatterns = [
    path('find/', FindRadioView.as_view(), name='find'),
    path('<int:pk>/', RadioDetailView.as_view(), name='detail'),
    path('create/', RadioCreateView.as_view(), name='create'),
    path('<int:tei>/card/', RadioCardView.as_view(), name='card'),
    path('example/card/', RadioCardExampleView.as_view(), name='example_card'),
    path('scan/', ScanQRCodeView.as_view(), name='scan'),

    path('lookup/', LookupView.as_view(), name='lookup'),
    path('selector/test', TemplateView.as_view(template_name="radio/selector/test.html"), name='selector_test'),
    path('selector/result/<int:pk>/', SelectorResultView.as_view(), name='selector_result'),

    path('image/<int:pk>_<str:type>.png/', QRImageView.as_view(), name='label_image'),

    path("decommissioning/request/", DecommissioningRequestView.as_view(), name="decommissioning_request"),

]

roip/urls.py
# roip/urls.py
from django.urls import path
from .views import LiveTxView

app_name = "roip"

urlpatterns = [
    path("live/", LiveTxView.as_view(), name="roip-live-tx"),
]

taqto/urls.py
from django.urls import path
from .views import *

app_name = 'taqto'

urlpatterns = [
    path('contacts/', ContactsDownloadView.as_view(), name='contacts_download'),
    path('contacts/<str:discipline_filter>/', ContactsDownloadView.as_view(), name='contacts_download_by_discipline'),
]

templates/base.html
{% extends "html5.html" %}

{% load bootstrap5 %}
{% load static %}

{% block base_extra_head %}
	<!-- Bootstrap CSS -->
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

    <!-- Bootstrap JavaScript  -->
    {% bootstrap_javascript %}
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
{% endblock %}

{% block body %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block container %}

  <div class="container-fluid container-md mt-4">

    <!-- Messages  -->
    {% for message in messages %}
      {% if "error" in message.tags %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% elif "success" in message.tags %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
      {% elif "warning" in message.tags %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {% elif "info" in message.tags %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
      {% else %}
        <div class="alert alert-secondary alert-dismissible fade show" role="alert">
      {% endif %}
        {{ message|safe }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
    
    {% block before_content %}{% endblock %}
    {% block content %} CONTENT {% endblock %}
    {% block after_content %}{% endblock %}
  </div>

{% endblock %}

{% block extra_script %}{% endblock %}

{% endblock %}

templates/base_backup.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% load static %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">


    <!-- Page title -->
    <title>{% block title %}Radio Asset Management{% endblock %}</title>

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    

    <!-- Bootstrap JavaScript  -->
    {% bootstrap_javascript %}

    {% block extra_head %}{% endblock %}

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">
        Radio Asset Management
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'inventory:posts_list' %}"><i class="bi bi-qr-code-scan"></i> Scanner</a></li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container mt-4">
    {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
    {% block before_content %}{% endblock %}
    {% block content %} CONTENT {% endblock %}
    {% block after_content %}{% endblock %}
  </div>
  
  {% block extra_script %}{% endblock %}

</body>
</html>

templates/html5.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% load static %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">


    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">


    <!-- Page title -->
    <title>{% block title %}Radio Asset Management{% endblock %}</title>

    {% block base_extra_head %}{% endblock %}
    
    {% block extra_head %}{% endblock %}

</head>

<body>

  {% block body %}{% endblock %}

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n%}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container mt-5 text-center">
  <h1>{% trans "Welkom bij Radio Asset Management" %}</h1>
  <p>{% trans "Start hier met beheren van de radio’s van Brandweer Brussel" %}</p>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}

{% block navbar %}
{% endblock %}

{% block body %}
<div class="vh-100 d-flex justify-content-center align-items-center" style="background-color: #e0e0e0;">
  <div class="card p-4 shadow" style="width: 350px;">
<h3 class="d-flex align-items-center justify-content-center mb-4">
  <img src="{% static 'icon.svg' %}" alt="Logo" height="60"> <!-- 2 lijnen hoog -->
  <div class="ms-3">
    <div>Radio Asset</div>
    <div>Management</div>
  </div>
</h3>
    <form method="post" action="{% url 'login' %}">
      {% csrf_token %}

      <!-- Username input -->
      <div class="form-outline mb-4">
        <input type="text" id="username" name="username" class="form-control" placeholder="Username" required />
      </div>

      <!-- Password input -->
      <div class="form-outline mb-4">
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required />
      </div>

      <!-- Submit button -->
      <button type="submit" class="btn btn-primary w-100">Login</button>
    </form>
  </div>
</div>
{% endblock %}

templates/navbar.html
{% load static i18n%}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid container-md">

    <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
      <img src="{% static 'icon.svg' %}" alt="Logo" height="30">
      <span class="ms-2">Radio Asset Management</span>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav me-2">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#"
             id="navbarInventoryDropdown"
             role="button"
             data-bs-toggle="dropdown"
             aria-expanded="false">
            <i class="bi bi-list-check"></i> {% trans "Inventory" %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarInventoryDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'organization:list_posts' %}">
                <i class="bi bi-building me-2"></i>{% trans "Posts" %}
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'fireplan:latest_inventory_per_vector' %}">
                <i class="fa fa-truck-medical me-2"></i>{% trans "Ziekenwagens" %}
              </a>
            </li>
          </ul>
        </li>

        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="radioDropdown" role="button" data-bs-toggle="dropdown">
              <i class="fa fa-walkie-talkie"></i> Radio
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="radioDropdown">
              <li><a class="dropdown-item" href="{% url 'radio:find' %}"><i class="bi bi-search"></i> {% trans "Find" %}</a></li>
              {% if perms.radio.add_radio %}
              <li><a class="dropdown-item" href="{% url 'radio:create' %}"><i class="bi bi-plus-circle"></i> {% trans "Add radio" %}</a></li>
              {% endif %}
              {% if perms.radio.can_create_decommission_requests %}
              <!--
                <li><a class="dropdown-item" href="{% url 'radio:decommissioning_request' %}"><i class="bi bi-slash-circle"></i> {% trans "Decommissioning request" %}</a></li>
              -->
              {% endif %}
            </ul>
          </li>
        {% endif %} 

        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="astridDropdown" role="button" data-bs-toggle="dropdown">
              <span class="svg-icon align-top">
                {% include "svg/astrid_logo.svg" %}
              </span> Astrid
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="astridDropdown">
              {% if perms.radio.can_upload_subscriptions %}
              <li><a class="dropdown-item" href="{% url 'astrid:upload_subscriptions' %}"><i class="bi bi-cloud-upload"></i> {% trans "Upload subscriptions" %}</a></li>
              <li><hr class="dropdown-divider"></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'astrid:vtei_request' %}"><i class="fa-solid fa-repeat"></i> {% trans "VTEI request" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'astrid:vtei_request' %}"><i class="fa-solid fa-shuffle"></i></i> {% trans "VTEI & VISSI request" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'astrid:activation_request' %}"><i class="fa-solid fa-circle-play"></i></i> {% trans "Activation request" %}</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'astrid:request_overview' %}"><i class="bi bi-list-ul"></i></i> {% trans "Overzicht van aanvragen" %}</a></li>

            </ul>
          </li>
        {% endif %}

        {% if perms.taqto.tacto_user %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="taqtoDropdown" role="button" data-bs-toggle="dropdown">
            <span class="svg-icon align-top">
              {% include "svg/airbus_logo.svg" %}
            </span> Taqto
          </a>

          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="taqtoDropdown">

            {% if perms.taqto.can_download_contacts %}
              <!-- Titel als "disabled" dropdown-item -->
              <li>
                <span class="dropdown-item text-muted disabled" style="pointer-events:none;">
                  <i class="bi bi-person-lines-fill"></i> {% trans "Download contacts" %}
                </span>
              </li>

              <!-- Fire -->
              <li>
                <a class="dropdown-item ps-4" href="{% url 'taqto:contacts_download_by_discipline' 'fire' %}">
                  <i class="bi bi-fire"></i> {% trans "Fire" %}
                </a>
              </li>

              <!-- Medical -->
              <li>
                <a class="dropdown-item ps-4" href="{% url 'taqto:contacts_download_by_discipline' 'medical' %}">
                  <i class="bi bi-heart-pulse"></i> {% trans "Medical" %}
                </a>
              </li>
            {% endif %}

          </ul>
        </li>
        {% endif %}


        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="helpdeskDropdown" role="button" data-bs-toggle="dropdown">
              <i class="bi bi-life-preserver"></i> Helpdesk
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="helpdeskDropdown">
              <li><a class="dropdown-item" href="{% url 'helpdesk:ticket_list' %}">
                <i class="bi bi-list-ul"></i> {% trans "Ticket overview" %}
              </a></li>
            </ul>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'roip-live-tx' %}active{% endif %}"
               href="{% url 'roip:roip-live-tx' %}">
              <i class="bi bi-broadcast"></i> {% trans "Live" %}
            </a>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown">
              <i class="bi bi-person-circle"></i> {{ user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
              {% language 'en' %}
              <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="bi bi-speedometer2"></i> {% trans "Admin" %}</a></li>
              {% endlanguage %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="bi bi-box-arrow-right"></i> {% trans "Logout" %}</a></li>
            </ul>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}"><i class="bi bi-box-arrow-in-right"></i> {% trans "Login" %}</a>
          </li>
        {% endif %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="langDropdown" role="button" data-bs-toggle="dropdown">
            <i class="bi bi-globe"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="langDropdown">
            {% if request.LANGUAGE_CODE != 'nl' %}
            <li>
              <a class="dropdown-item" href="/nl/">
                <img src="{% static 'flags/nl.svg' %}" class="align-text-bottom" height="16" alt="Nederlands"> Nederlands
              </a>
            </li>
            {% endif %}
            {% if request.LANGUAGE_CODE != 'fr' %}
            <li>
              <a class="dropdown-item" href="/fr/">
                <img src="{% static 'flags/fr.svg' %}" class="align-text-bottom" height="16" alt="Français"> Français
              </a>
            </li>
            {% endif %}
            {% if request.LANGUAGE_CODE != 'en' %}
            <li>
              <a class="dropdown-item" href="/en/">
                <img src="{% static 'flags/gb.svg' %}" class="align-text-bottom" height="16" alt="English"> English
              </a>
            </li>
            {% endif %}
          </ul>
        </li>



      </ul>
    </div>

  </div>
</nav>